version: "3.8"
services:
  discord:
    # build: .
    image: vieribotglobal-discord
    restart: always
    volumes:
      - ./Discord/datas:/usr/src/bot/Discord/datas
      - ./Discord/auth.json:/usr/src/bot/Discord/auth.json:ro
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-file: 2
        max-size: "10m"
