version: '3.9' # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - '8000:5000'
    volumes:
      - ./datas:/usr/src/bot/Discord/datas
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
